paperclip_csv_test/config/routes.rb
Rails.application.routes.draw do
  resources :jobs do
    post :confirm, on: :collection
  end

end

paperclip_csv_test/app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessor :tempfile_path
  has_attached_file :csv
  validates_attachment_presence :csv
  validates_attachment_content_type :csv, :content_type => ['text/csv','text/comma-separated-values','application/csv','text/plain']
end

paperclip_csv_test/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs/confirm
  def confirm
    @job = Job.new(job_params)
    @job.tempfile_path = job_params[:csv].path
    if @job.valid?
      render :confirm
    else
      render :new
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    upload_file = ActionDispatch::Http::UploadedFile.new(
      filename: job_params[:csv_file_name],
      type: 'text/csv',
      tempfile: File.open(job_params[:tempfile_path])
    )

    @job = Job.new(job_params.merge(csv: upload_file))

    if @job.save
      redirect_to @job, notice: 'Job was successfully created.'
    else
      redirect_to :new, notice: 'Failed.'
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :priority, :csv, :tempfile_path, :csv_file_name)
    end
end

paperclip_csv_test/app/helpers/jobs_helper.rb
module JobsHelper
end

paperclip_csv_test/app/views/jobs/_form.html.erb
<%= form_for(@job, url: confirm_jobs_path, method: :post) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :csv %><br>
    <%= f.file_field :csv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

paperclip_csv_test/app/views/jobs/confirm.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :name %>
  <%= f.hidden_field :priority %>
  <%= f.hidden_field :tempfile_path %>
  <%= f.hidden_field :csv_file_name %>

  <div class="field">
    <%= f.label :name %><br>
    <p><%= @job.name %></p>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <p><%= @job.priority %></p>
  </div>
  <div class="field">
    <%= f.label :csv %><br>
    <p><%= @job.csv_file_name %></p>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

paperclip_csv_test/app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

paperclip_csv_test/app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.priority %></td>
        <td><%= link_to job.csv_file_name, job.csv.url %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

paperclip_csv_test/app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

paperclip_csv_test/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @job.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @job.priority %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>